-- DML Queries
INSERT INTO users (name,email,password,phone,role_id,status_id) VALUES (?, ?, ?, ?, ?, 1);
INSERT INTO customers(user_id) VALUES(?);
UPDATE users SET password=? WHERE id=?;
UPDATE orders SET order_status_id=? WHERE id=?;
INSERT INTO products (seller_id,category_id,name,slug,description,price,status) VALUES (?, ?, ?, ?, ?, ?, 'active');
INSERT INTO inventory (product_id,stock) VALUES (?,?);
INSERT INTO product_images (product_id,image_data,image_type) VALUES (?, ?, ?);
UPDATE products SET name=?,description=?,price=?,category_id=?,thumbnail=? WHERE id=?;
UPDATE inventory SET stock=? WHERE product_id=?;
UPDATE products SET name=?,description=?,price=?,category_id=? WHERE id=?;
UPDATE inventory SET stock=? WHERE product_id=?;
DELETE FROM cart_items WHERE product_id=?;
DELETE FROM wishlist_items WHERE product_id=?;
DELETE FROM reviews WHERE product_id=?;
DELETE FROM order_items WHERE product_id=?;
DELETE FROM product_images WHERE product_id=?;
DELETE FROM inventory WHERE product_id=?;
DELETE FROM products WHERE id=?;
INSERT INTO addresses (user_id,full_name,phone,country_id,province_id,city_id,postal_code,address_line_1,address_line_2,landmark,address_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO orders (customer_id,address_id,order_number,subtotal,shipping_fee,tax,discount,total_amount,payment_method_id,payment_status_id,order_status_id) VALUES (?, ?, ?, ?, 0, 0, 0, ?, 1, 1, 1);
INSERT INTO order_items (order_id,product_id,seller_id,quantity,price,subtotal) VALUES ?;
UPDATE inventory SET stock = stock - ? WHERE product_id = ?;
DELETE ci FROM cart_items ci JOIN carts c ON ci.cart_id = c.id WHERE c.customer_id = ?;
INSERT INTO carts(customer_id) VALUES(?);
UPDATE cart_items SET quantity = quantity + ? WHERE id = ?;
INSERT INTO cart_items (cart_id,product_id,quantity) VALUES (?, ?, ?);
UPDATE cart_items SET quantity = quantity + 1 WHERE id=?;
UPDATE cart_items SET quantity = CASE WHEN quantity > 1 THEN quantity - 1 ELSE 1 END WHERE id=?;
DELETE FROM cart_items WHERE id=?;
INSERT INTO reviews (customer_id,product_id,rating,comment) VALUES (?, ?, ?, ?);
